// <auto-generated />
namespace CountingKs.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class M1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M1));
        
        string IMigrationMetadata.Id
        {
            get { return "201902071735002_M1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
